In [1]:
post_data = {
    'title': 'Sample Post Title',
    'text': 'This is the sample text for the post.',
    'image': 'path/to/image.jpg'  # Replace with the actual path to your image
}

print(post_data)

{'title': 'Sample Post Title', 'text': 'This is the sample text for the post.', 'image': 'path/to/image.jpg'}


In [13]:
import pandas as pd

# Define the path to the dataset
dataset_path = '/Users/macbookair/Documents/Project/fItneSS_us/recommendation/datasets/MIND/MINDlarge_dev/news.tsv'

# Load the dataset
dataset = pd.read_csv(dataset_path, sep='\t', header=None)
dataset.columns = ['news_id', 'category', 'subcategory', 'title', 'abstract', 'url', 'title_entities', 'abstract_entities']
dataset.head()

news_id   category      subcategory  \
0  N88753  lifestyle  lifestyleroyals   
1  N23144     health       weightloss   
2  N86255     health          medical   
3  N93187       news        newsworld   
4  N75236     health           voices   

                                               title  \
0  The Brands Queen Elizabeth, Prince Charles, an...   
1                      50 Worst Habits For Belly Fat   
2  Dispose of unwanted prescription drugs during ...   
3  The Cost of Trump's Aid Freeze in the Trenches...   
4  I Was An NBA Wife. Here's How It Affected My M...   

                                            abstract  \
0  Shop the notebooks, jackets, and more that the...   
1  These seemingly harmless habits are holding yo...   
2                                                NaN   
3  Lt. Ivan Molchanets peeked over a parapet of s...   
4  I felt like I was a fraud, and being an NBA wi...   

                                             url  \
0  https://assets.msn.com/labs/mind/AAGH0ET.html   
1  https://assets.msn.com/labs/mind/AAB19MK.html   
2  https://assets.msn.com/labs/mind/AAISxPN.html   
3  https://assets.msn.com/labs/mind/AAJgNsz.html   
4  https://assets.msn.com/labs/mind/AACk2N6.html   

                                      title_entities  \
0  [{"Label": "Prince Philip, Duke of Edinburgh",...   
1  [{"Label": "Adipose tissue", "Type": "C", "Wik...   
2  [{"Label": "Drug Enforcement Administration", ...   
3                                                 []   
4                                                 []   

                                   abstract_entities  
0                                                 []  
1  [{"Label": "Adipose tissue", "Type": "C", "Wik...  
2                                                 []  
3  [{"Label": "Ukraine", "Type": "G", "WikidataId...  
4  [{"Label": "National Basketball Association", ...

In [32]:
dataset['img_path'] = '/Users/macbookair/Documents/Project/fItneSS_us/recommendation/datasets/celebA_50k/' + str(dataset.index[0]+1).zfill(6) + '.jpg'
dataset.head()

news_id   category      subcategory  \
0  N88753  lifestyle  lifestyleroyals   
1  N23144     health       weightloss   
2  N86255     health          medical   
3  N93187       news        newsworld   
4  N75236     health           voices   

                                               title  \
0  The Brands Queen Elizabeth, Prince Charles, an...   
1                      50 Worst Habits For Belly Fat   
2  Dispose of unwanted prescription drugs during ...   
3  The Cost of Trump's Aid Freeze in the Trenches...   
4  I Was An NBA Wife. Here's How It Affected My M...   

                                            abstract  \
0  Shop the notebooks, jackets, and more that the...   
1  These seemingly harmless habits are holding yo...   
2                                                NaN   
3  Lt. Ivan Molchanets peeked over a parapet of s...   
4  I felt like I was a fraud, and being an NBA wi...   

                                             url  \
0  https://assets.msn.com/labs/mind/AAGH0ET.html   
1  https://assets.msn.com/labs/mind/AAB19MK.html   
2  https://assets.msn.com/labs/mind/AAISxPN.html   
3  https://assets.msn.com/labs/mind/AAJgNsz.html   
4  https://assets.msn.com/labs/mind/AACk2N6.html   

                                      title_entities  \
0  [{"Label": "Prince Philip, Duke of Edinburgh",...   
1  [{"Label": "Adipose tissue", "Type": "C", "Wik...   
2  [{"Label": "Drug Enforcement Administration", ...   
3                                                 []   
4                                                 []   

                                   abstract_entities  \
0                                                 []   
1  [{"Label": "Adipose tissue", "Type": "C", "Wik...   
2                                                 []   
3  [{"Label": "Ukraine", "Type": "G", "WikidataId...   
4  [{"Label": "National Basketball Association", ...   

                                            img_path  
0  /Users/macbookair/Documents/Project/fItneSS_us...  
1  /Users/macbookair/Documents/Project/fItneSS_us...  
2  /Users/macbookair/Documents/Project/fItneSS_us...  
3  /Users/macbookair/Documents/Project/fItneSS_us...  
4  /Users/macbookair/Documents/Project/fItneSS_us...

In [33]:
print(dataset['img_path'][0])

/Users/macbookair/Documents/Project/fItneSS_us/recommendation/datasets/celebA_50k/000001.jpg


In [34]:
#exporting the dataset
dataset.to_csv('/Users/macbookair/Documents/Project/fItneSS_us/recommendation/datasets/news_with_img_path.csv', sep='\t', index=False, header=False)

In [1]:
import pandas as pd

# Define the path to the dataset
dataset_path = '/Users/macbookair/Documents/Project/fItneSS_us/recommendation/datasets/news_with_img_path.csv'

# Load the dataset
dataset = pd.read_csv(dataset_path, sep='\t', header=None)
dataset.columns = ['news_id', 'category', 'subcategory', 'title', 'abstract', 'url', 'title_entities', 'abstract_entities', 'img_path']
dataset.head()

news_id   category      subcategory  \
0  N88753  lifestyle  lifestyleroyals   
1  N23144     health       weightloss   
2  N86255     health          medical   
3  N93187       news        newsworld   
4  N75236     health           voices   

                                               title  \
0  The Brands Queen Elizabeth, Prince Charles, an...   
1                      50 Worst Habits For Belly Fat   
2  Dispose of unwanted prescription drugs during ...   
3  The Cost of Trump's Aid Freeze in the Trenches...   
4  I Was An NBA Wife. Here's How It Affected My M...   

                                            abstract  \
0  Shop the notebooks, jackets, and more that the...   
1  These seemingly harmless habits are holding yo...   
2                                                NaN   
3  Lt. Ivan Molchanets peeked over a parapet of s...   
4  I felt like I was a fraud, and being an NBA wi...   

                                             url  \
0  https://assets.msn.com/labs/mind/AAGH0ET.html   
1  https://assets.msn.com/labs/mind/AAB19MK.html   
2  https://assets.msn.com/labs/mind/AAISxPN.html   
3  https://assets.msn.com/labs/mind/AAJgNsz.html   
4  https://assets.msn.com/labs/mind/AACk2N6.html   

                                      title_entities  \
0  [{"Label": "Prince Philip, Duke of Edinburgh",...   
1  [{"Label": "Adipose tissue", "Type": "C", "Wik...   
2  [{"Label": "Drug Enforcement Administration", ...   
3                                                 []   
4                                                 []   

                                   abstract_entities  \
0                                                 []   
1  [{"Label": "Adipose tissue", "Type": "C", "Wik...   
2                                                 []   
3  [{"Label": "Ukraine", "Type": "G", "WikidataId...   
4  [{"Label": "National Basketball Association", ...   

                                            img_path  
0  /Users/macbookair/Documents/Project/fItneSS_us...  
1  /Users/macbookair/Documents/Project/fItneSS_us...  
2  /Users/macbookair/Documents/Project/fItneSS_us...  
3  /Users/macbookair/Documents/Project/fItneSS_us...  
4  /Users/macbookair/Documents/Project/fItneSS_us...

In [2]:
dataset.loc[0]['img_path'],dataset.loc[0]['title'],dataset.loc[0]['abstract']

('/Users/macbookair/Documents/Project/fItneSS_us/recommendation/datasets/celebA_50k/000001.jpg',
 'The Brands Queen Elizabeth, Prince Charles, and Prince Philip Swear By',
 "Shop the notebooks, jackets, and more that the royals can't live without.")

In [3]:
from postside import post_embeddings
from resnet import get_image_embeddings
get_image_embeddings('/Users/macbookair/Documents/Project/fItneSS_us/recommendation/datasets/celebA_50k/000001.jpg')

/opt/anaconda3/lib/python3.12/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


tensor([[0.2286, 0.0000, 0.0024,  ..., 0.0000, 0.0000, 0.0000]])

In [4]:
get_image_embeddings(dataset.loc[0]['img_path'])

tensor([[0.2286, 0.0000, 0.0024,  ..., 0.0000, 0.0000, 0.0000]])

In [5]:
post_embeddings(dataset.loc[0]['img_path'],dataset.loc[0]['title'],dataset.loc[0]['abstract'])

/opt/anaconda3/lib/python3.12/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


tensor([[ 0.2286,  0.0000,  0.0024,  ..., -0.1980,  0.2810,  0.1527]])

In [6]:
from postside import tensor_to_bytes

In [7]:
tensor_to_bytes(post_embeddings(dataset.loc[0]['img_path'],dataset.loc[0]['title'],dataset.loc[0]['abstract']))

/opt/anaconda3/lib/python3.12/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/opt/anaconda3/lib/python3.12/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


b'%!j>\x00\x00\x00\x00\n\xa4\x1a;\x00\x00\x00\x00\x00\x00\x00\x00\xd0m\x0e=\x00\x00\x00\x00\x1dS\xca?\x00\x00\x00\x00\xfb\xef\xfc<\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04p\xe2<\x00\x00\x00\x00\x00\x00\x00\x00\xdb\x8e$;\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x07\x13Q>\x00\x00\x00\x00\x00\x00\x00\x00\x05Gj:\x00\x00\x00\x00\x00\x00\x00\x00\xc4\xe4`=\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00J\xf4\xf4=\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xb3\xb9\xa0=\x00\x00\x00\x00\x00\x00\x00\x00v\xc7\xfd?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00&V\xcb>\x00\x00\x00\x00\x00\x00\x00\x00aI9<\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0

In [10]:
import pandas as pd
import numpy as np
import torch
import tensorflow as tf

print(pd.__version__)
print(tf.__version__)
print(torch.__version__)

2.2.2
2.17.0
2.4.0
